sonar.projectKey=sistema_registro
sonar.projectName=Sistema Registro Django
sonar.projectVersion=1.0

sonar.sources=usuarios

sonar.python.version=3.12

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/migrations/**,**/__pycache__/**

sonar.python.coverage.reportPaths=coverage.xml